# Generated by Django 6.0.2 on 2026-02-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('adult_ticket', 'Adult Ticket'), ('child_ticket', 'Child Ticket'), ('vehicle_pass', 'Vehicle Pass')], max_length=100)),
                ('stripe_checkout_session_id', models.CharField(max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owning_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_orders', to=settings.AUTH_USER_MODEL)),
                ('purchasing_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchased_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
