# Generated by Django 6.0.2 on 2026-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(choices=[('adult_ticket', 'Adult Ticket'), ('child_ticket', 'Child Ticket'), ('vehicle_pass', 'Vehicle Pass')], max_length=100),
        ),
    ]
