# Generated by Django 6.0.2 on 2026-02-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_shift_shiftassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='event',
        ),
    ]
