# Generated by Django 6.0.2 on 2026-02-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_shift_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('role', 'start_time', 'end_time')},
        ),
    ]
