# Generated by Django 6.0.2 on 2026-02-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shift_unique_role_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_shifts_per_user',
            field=models.PositiveIntegerField(default=0, help_text='Maximum shifts per user (0 = unlimited)'),
        ),
    ]
